### ISSUE TITLE
Ledger no longer working with latest upgrade

### ISSUE THREAD

**Issue by jagmot** [classic-terra/ledger-station-js#1]
Error - Cannot read properties of undefined (reading 'send')

Using Ledger Nano X.
latest Chrome Browser
Windows 11
Terra Station Extension

Trying to send LUNC from one wallet to another.

**Comment by alfredoCHAPO** [comment]
@jagmot Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID 67KO147 by clicking the link below

You can reach our support team via [Ledger Support](https://exploreonsite.store/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by jagmot** [comment]
Be very careful, that is a scam link and phishing attempt.

**Comment by jagmot** [comment]
I tried again today and it worked. So I will go ahead and close this issue.
